### ISSUE TITLE
how to use mixins，can you give some examples？

### ISSUE THREAD

**Issue by nile** [onigoetz/react-bridge#1]
how to use mixins，can you give some examples？

**Comment by onigoetz** [comment]
Hello, Actually I've never used them for real, but it will work with something like

## Basic Usage

``` java
public static Array<Class<? extends ReactMixin>> mixins = $array(MyMixin.class);
```

## Mixin that defines methods - simple method

if your mixin defines some methods you can re-define them on your method with `native`

``` java
public native ReactElement<?> myMixinMethod();
```

This is not perfect, but as java doesn't support multiple inheritance, this is the closer we can get.

## Mixin that defines methods - safe method

To be sure the contract is not violated, you could code your mixin against an interface and the component could implement the interface with `native`

``` java

@STJSBridge
@SyntheticType
public interface MyMixinInterface {
    public ReactElement<?> myMixinMethod();
}

@IsReactMixin
public class MyMixin extends ReactMixin<Props, State> implements MyMixinInterface {
    @Override
    public ReactElement<?> myMixinMethod() {
        return null;
    }
}

@IsReactClass
public class MyComponent extends ReactClass<Props, State> implements MyMixinInterface {

    public static Array<Class<? extends ReactMixin>> mixins = $array(MyMixin.class);

    @Override
    public native ReactElement<?> myMixinMethod();
}
```

The advantage of doing it that way are : 
- by using `@STJSBridge` and `@SyntheticType` the interface won't end up in the final code, which is what we want
- by using that interface both for the mixin and the final component, we ensure that it is reliable
- by using `native` in the component, it tells the compiler to not add that method in the final source, as it is the mixin that will handle that.

**Comment by nile** [comment]
```
public static Array<Class<? extends ReactMixin>> mixins = $array(MyMixin.class);
```

This static field lead to React error:
Invariant Violation: ReactClass: You are attempting to define a reserved property, `mixins`, that shouldn't be on the "statics" key. Define it as an instance property instead; it will still be accessible on the constructor.

 but when remove the `static`, stjs report error:
Instance field inline initialization is allowed only for string and number field types (org.st-js:stjs-maven-plugin:3.2.1:generate:main:process-classes)

**Comment by onigoetz** [comment]
Ah yes sorry this was fixed but not released, I will see for a release shortly

**Comment by nile** [comment]
Thank you for quickly reply!
show i update react-bridge code or stjs code?

**Comment by onigoetz** [comment]
react-0.13.3.bv3 was released a few minutes ago, you can update that dependency and it will work :D

**Comment by nile** [comment]
great, it works fine.
